name: ai_vision_plus
description: Ai Assistant Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  tflite: ^1.1.2
  camera: ^0.10.0+1
  image_picker: ^0.8.5+3
  flutter_tts: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/labels.txt
    - assets/metadata_V2.tflite
    - assets/models/ssd_mobilenet.tflite
    - assets/models/labels.txt